In [1]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [10]:
import pymysql
conn = pymysql.connect(
    host = 'localhost',
    port = 3306,
    user = 'root',
    password = '0000',
    db = 'test',
    charset = 'utf8mb4'
)

In [11]:
cur = conn.cursor()

In [13]:
cur.execute("SELECT * FROM sales")

0

In [14]:
cur.execute("""CREATE TABLE customer (
                  Id INT PRIMARY KEY AUTO_INCREMENT,
                  name VARCHAR(50) NOT NULL,
                  email VARCHAR(200))""")

0

In [15]:
cur.execute("INSERT INTO customer (name) VALUES ('류진수')")

1

In [25]:
conn.commit()

In [23]:
while (True) :
    name = input("사용자이름은? :")
    if name == "":
        print("사용자 이름은 필수  입력값입니다.")
        continue
    email = input("사용자의 이메일 주소를 입력해주세요.")
    query = "INSERT INTO customer(name,email) VALUES('"+name+"','"+email+"')"
    cur.execute(query)
    break;

사용자이름은? : tt
사용자의 이메일 주소를 입력해주세요. tt

In [26]:
cur.execute("SELECT * FROM customer")

print("ID     이름     이메일")
print("----------------------")

while (True) :
     row = cur.fetchone() #데이터를 한행씩 
     if row == None:
         break
     cus_id = row[0] 
     name = row[1]
     email = row[2]
     print("%2s     %10s   %10s"%(cus_id,name,email))

ID     이름     이메일
----------------------
 1            류진수         None
 2           asdf         asdf
 3           asdf         asdf
 4           asdf         asdf
 5           asdf         asdf
 6           asdf         asdf
 7           asdf         asdf
 8             tt           tt

In [27]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\qhwhr\anaconda3\envs\dba4\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [30]:
import pandas as pd
cur.execute("SELECT * FROM customer")
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

   Id  name email
0   1   류진수  None
1   2  asdf  asdf
2   3  asdf  asdf
3   4  asdf  asdf
4   5  asdf  asdf
5   6  asdf  asdf
6   7  asdf  asdf
7   8    tt    tt

In [ ]:
# country 테이블에서
# GovernmentForm 필드 기준으로 내림차순으로 정렬한 후
# SurfaceArea 필드 기준으로 오름차순 정렬하여 조회

In [35]:
conn = pymysql.connect(
    host = 'localhost',
    port = 3306,
    user = 'root',
    password = '0000',
    db = 'world',
    charset = 'utf8mb4'
)
cur = conn.cursor()
query = """
SELECT Name,SurfaceArea,GovernmentForm
FROM country
ORDER BY GovernmentForm DESC, SurfaceArea ASC
"""
cur.execute(query)

result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

                         Name  SurfaceArea           GovernmentForm
0              American Samoa       199.00             US Territory
1        Virgin Islands, U.S.       347.00             US Territory
2                        Guam       549.00             US Territory
3     Cocos (Keeling) Islands        14.00   Territory of Australia
4              Norfolk Island        36.00   Territory of Australia
..                        ...          ...                      ...
234  Northern Mariana Islands       464.00   Commonwealth of the US
235               Puerto Rico      8875.00   Commonwealth of the US
236                Antarctica  13120000.00         Co-administrated
237                 Palestine      6257.00          Autonomous Area
238                East Timor     14874.00  Administrated by the UN

[239 rows x 3 columns]

In [ ]:
# country 테이블에서
# Continent 필드가 'Africa'인 데이터 중에
# Population 기준으로 오름차순 정렬한 후
# Name, Population 데이터

In [37]:
query = """
SELECT Name, Population
FROM country
WHERE Continent = 'Africa'
ORDER BY Population ASC
"""
cur.execute(query)
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

                                     Name  Population
0          British Indian Ocean Territory           0
1                            Saint Helena        6000
2                              Seychelles       77000
3                   Sao Tome and Principe      147000
4                                 Mayotte      149000
5                          Western Sahara      293000
6                              Cape Verde      428000
7                       Equatorial Guinea      453000
8                                 Comoros      578000
9                                Djibouti      638000
10                                Réunion      699000
11                              Swaziland     1008000
12                              Mauritius     1158000
13                          Guinea-Bissau     1213000
14                                  Gabon     1226000
15                                 Gambia     1305000
16                               Botswana     1622000
17                                Namibia     1726000
18                                Lesotho     2153000
19                             Mauritania     2670000
20                                  Congo     2943000
21                                Liberia     3154000
22               Central African Republic     3615000
23                                Eritrea     3850000
24                                   Togo     4629000
25                           Sierra Leone     4854000
26                 Libyan Arab Jamahiriya     5605000
27                                  Benin     6097000
28                                Burundi     6695000
29                                 Guinea     7430000
30                                   Chad     7651000
31                                 Rwanda     7733000
32                                 Zambia     9169000
33                                Senegal     9481000
34                                Tunisia     9586000
35                                Somalia    10097000
36                                  Niger    10730000
37                                 Malawi    10925000
38                                   Mali    11234000
39                               Zimbabwe    11669000
40                           Burkina Faso    11937000
41                                 Angola    12878000
42                          Côte d’Ivoire    14786000
43                               Cameroon    15085000
44                             Madagascar    15942000
45                             Mozambique    19680000
46                                  Ghana    20212000
47                                 Uganda    21778000
48                                Morocco    28351000
49                                  Sudan    29490000
50                                  Kenya    30080000
51                                Algeria    31471000
52                               Tanzania    33517000
53                           South Africa    40377000
54  Congo, The Democratic Republic of the    51654000
55                               Ethiopia    62565000
56                                  Egypt    68470000
57                                Nigeria   111506000

In [ ]:
# country 테이블에서 Continent 필드로 그룹화하고
# GNP 평균값을 소수점 2자로 반올림하여 조회하고 이름을 avg_GNP로 출력

In [38]:
query = """
SELECT Continent, ROUND(AVG(GNP), 2) AS avg_GNP
FROM country
GROUP BY Continent
"""
cur.execute(query)
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

       Continent    avg_GNP
0  North America  261854.79
1           Asia  150105.73
2         Africa   10006.47
3         Europe  206497.07
4  South America  107991.00
5        Oceania   14991.95
6     Antarctica       0.00

In [ ]:
# country 테이블에서 Region 필드로 그룹화하고
# 나라의 개수가 15이상 20이하인 데이터를 count_reg로 하여 내림차순으로 조회

In [39]:
query = """
SELECT Region, COUNT(*) AS count_reg
FROM country
GROUP BY Region
HAVING COUNT(*) BETWEEN 15 AND 20
ORDER BY count_reg DESC
"""
cur.execute(query)
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

            Region  count_reg
0   Eastern Africa         20
1      Middle East         18
2   Western Africa         17
3  Southern Europe         15

In [ ]:
# country 테이블의 각 국가마다
# 해당 국가에 소속된 도시들의 평균 인구를 city 테이블을 이용하여 조회

In [41]:
query = """
SELECT c.Name AS Country, AVG(ci.Population) AS Average_City_Population
FROM country c
JOIN city ci ON c.Code = ci.CountryCode
GROUP BY c.Name
"""
cur.execute(query)
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

          Country Average_City_Population
0           Aruba              29034.0000
1     Afghanistan             583025.0000
2          Angola             512320.0000
3        Anguilla                778.0000
4         Albania             270000.0000
..            ...                     ...
227         Yemen             290616.6667
228    Yugoslavia             273688.3750
229  South Africa             345372.0455
230        Zambia             353357.1429
231      Zimbabwe             455070.0000

[232 rows x 2 columns]

In [ ]:
# country 테이블의 Frace의 국가코드를 이용하여
# city 테이블의 'France'의 모든 도시의 이름 출력

In [42]:
query = """
SELECT ci.Name AS CityName
FROM city ci
JOIN country c ON ci.CountryCode = c.Code
WHERE c.Name = 'France'
"""
cur.execute(query)
result = cur.fetchall()
columns = [col[0] for col in cur.description] 
df = pd.DataFrame(result,columns = columns) 
df

                CityName
0                  Paris
1              Marseille
2                   Lyon
3               Toulouse
4                   Nice
5                 Nantes
6             Strasbourg
7            Montpellier
8               Bordeaux
9                 Rennes
10              Le Havre
11                 Reims
12                 Lille
13            St-Étienne
14                Toulon
15              Grenoble
16                Angers
17                 Dijon
18                 Brest
19               Le Mans
20      Clermont-Ferrand
21                Amiens
22       Aix-en-Provence
23               Limoges
24                 Nîmes
25                 Tours
26          Villeurbanne
27                  Metz
28              Besançon
29                  Caen
30               Orléans
31              Mulhouse
32                 Rouen
33  Boulogne-Billancourt
34             Perpignan
35                 Nancy
36               Roubaix
37            Argenteuil
38             Tourcoing
39             Montreuil

In [ ]:
# world DB의 city와 country 테이블과 이용하여
# 도시 인구 비율 계산 함수 (도시인구/해당 국가의 인구)

In [48]:
conn = pymysql.connect(
    host = 'localhost',
    port = 3306,
    user = 'root',
    password = '0000',
    db = 'world',
    charset = 'utf8mb4'
)
cur = conn.cursor()
def city_pop_ratio(city_name):
    cur.execute(f""" SELECT c.Population, t.Population
                    FROM city c JOIN country t ON c.CountryCode = t.Code
                    WHERE c.Name='{city_name}'""")
    city_pop, country_pop = cur.fetchone() 
    return round(city_pop/country_pop*100,2)

In [49]:
    city_pop_ratio("Seoul")

21.31